spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
    platform: postgresql
    # 下面为连接池的补充设置，应用到上面所有数据源中
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true

  mail:
    host: smtp.exmail.qq.com #发送邮件服务器
    username: tangzhiming@linkfin-tech.com #QQ邮箱
    password: 4ezsqDWFmfGEyazv #客户端授权码
    protocol: smtp #发送邮件协议
#    default-encoding: utf-8
    default-encoding: gbk
    properties:
      mail:
        smtp:
          auth: true
          port: 465 #端口号465或587
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
        display:
          sendmail: Javen #可以任意
          sendname: Spring Boot Guide Email #可以任意

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.zlhj.pm.model
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

swagger:
  enable: true

api-url: /api

# 是否启用 Dataway 功能（必选：默认false）
HASOR_DATAQL_DATAWAY: true
# 是否开启 Dataway 后台管理界面（必选：默认false）
HASOR_DATAQL_DATAWAY_ADMIN: true
# dataway  API工作路径（可选，默认：/api/）
HASOR_DATAQL_DATAWAY_API_URL: /api/
# dataway-ui 的工作路径（可选，默认：/interface-ui/）
HASOR_DATAQL_DATAWAY_UI_URL: /interface-ui/
# SQL执行器方言设置（可选，建议设置）
HASOR_DATAQL_FX_PAGE_DIALECT: postgresql